### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by YoungPle** [Broadroad/map#2]
map_t *data = (map_t*)malloc(sizeof(map_t));
    data->key = (char*)malloc(sizeof(key));
    strcpy(data->key, key);
    data->val = (char*)malloc(sizeof(val));
    strcpy(data->val, val);

sizeof???

**Comment by Broadroad** [comment]
@YoungPle  I don't know what do you mean. Could you please describe clearly your issue or create a PR?

**Comment by wanglijie95** [comment]
@Broadroad 
I think it's a bug when you use malloc. 
`data->key = (char*)malloc(sizeof(key));`
key is char*, so sizeof(char*) is 4 or 8. I think it's should be:
`data->key = (char*)malloc((strlen(key) + 1) * sizeof(char));`

**Comment by Broadroad** [comment]
@YoungPle @wanglijie95 Thanks for your comments, it is a bug. Since sizeof(pointer) will only be constant. Thanks a lot.
