### ISSUE TITLE
Memory leak in put  function

### ISSUE THREAD

**Issue by jiapng** [Broadroad/map#3]
Memory leak in 'put'  function when  key is already in map

**Comment by RadinLy** [comment]
@jiapng  I also met, have you solved it

**Comment by Broadroad** [comment]
Thank u guys. I will fix it.

**Comment by RadinLy** [comment]
@kangting  不好意思，昨天我遇到的问题是没有循环释放导致的内存泄漏。希望你能把下面这个代码放入到example中，这个可以解决map未释放而导致内存泄露

请将该方法放入map.h 中，函数中的node为
`struct map {

    struct rb_node node;

    char *key;

    char *val;

};`
结构体中的node


``/*

描述：删除整颗红黑树

*/

void map_destory(root_t *root)

{

    rb_node_t *free_node = NULL, *tmp_node = NULL;

    map_t *nodeFree = NULL;



    for(free_node = rb_first(root); free_node; )

    {

        tmp_node = rb_next(free_node);

        nodeFree = rb_entry(free_node, map_t,node);

        rb_erase(free_node, root);

        map_free(nodeFree);

        free_node = tmp_node;

    }

}

``

**Comment by jiapng** [comment]
@RadinLy 示例中没有释放map的接口，我也是这样释放的，另外为了方便使用，我另加了一个update的接口，用于当key已经存在map中时，更新map中的值。

**Comment by Broadroad** [comment]
I already update the code, when the key is duplicated, it will update to the new value.

**Comment by RadinLy** [comment]
@jiapng  请问你能把update的代码发出来让我学习一下么？

**Comment by RadinLy** [comment]
> @RadinLy 示例中没有释放map的接口，我也是这样释放的，另外为了方便使用，我另加了一个update的接口，用于当key已经存在map中时，更新map中的值。

你好，当时我使用的map_frist方式释放整个map,会出现free 报错，我更新了最新方式的释放map的方式，经过验证，没有使用问题。

**Comment by RadinLy** [comment]
> I already update the code, when the key is duplicated, it will update to the new value.

你好，我之前发布的map_first的方式 释放整个map，会出现free报错，我更新了最新的释放map方式，经过验证，没有使用问题
